### ISSUE TITLE
Issue 3: CI/CD Pipeline for Legacy Application

### ISSUE THREAD

**Issue by chrishawl** [chrishawl/asp-net-upgrade-sample#3]
**Priority**: High  
**Estimated Effort**: 3-5 hours  
**Dependencies**: Issue 2

**Description**: Establish GitHub Actions pipeline for the .NET Framework version to ensure consistent builds and test execution.

**Tasks**-
- [ ] Add gitignore file for .net framework and .net 8
- [ ] Create `.github/workflows/dotnet-framework.yml`
- [ ] Configure Windows runner for .NET Framework builds
- [ ] Add build, test, and artifact generation steps
- [ ] Configure test result reporting
- [ ] Add code coverage reporting

**Acceptance Criteria**:
- [ ] Pipeline builds .NET Framework project successfully
- [ ] All unit tests run and results are reported
- [ ] Code coverage metrics are collected
- [ ] Artifacts are generated for deployments
- [ ] Pipeline runs on PR and main branch commits

**Pipeline Structure**:
```yaml
name: .NET Framework CI/CD
on: [push, pull_request]
jobs:
  build-and-test:
    runs-on: windows-latest
    steps:
      - name: Checkout
      - name: Setup MSBuild
      - name: Restore NuGet packages
      - name: Build solution
      - name: Run tests
      - name: Generate coverage report
```
